#!/usr/bin/env python3
"""
Визуализация данных и генерация HTML-отчета
Создает красивые графики и HTML-страницу

Измени для твоего стиля отчетов!
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')  # Без GUI
from datetime import datetime
import os

def visualize():
    print(f"[{datetime.now()}] Начало генерации отчета...")
    
    # Загружаем обработанные данные
    df = pd.read_csv("output/processed_data.csv")
    
    # Создаем папку для отчетов
    os.makedirs("reports", exist_ok=True)
    
    # Создаем красивый HTML-отчет
    html_content = f"""
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализ данных - {datetime.now().strftime('%Y-%m-%d')}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            text-align: center;
        }}
        .card {{
            background: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .metric {{
            display: inline-block;
            margin: 10px;
            padding: 15px;
            background: #4CAF50;
            color: white;
            border-radius: 8px;
            text-align: center;
            min-width: 150px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background: #667eea;
            color: white;
        }}
        .chart {{
            width: 100%;
            height: 400px;
            margin-top: 30px;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Анализ данных</h1>
        <p>Сгенерировано: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <p>Источник: OpenClaw Workspace</p>
    </div>
    
    <div class="card">
        <h2>📈 Сводка</h2>
        <p><strong>Всего записей:</strong> {len(df)}</p>
        <p><strong>Столбцов:</strong> {len(df.columns)}</p>
        <div>
            {''.join(f'<div class="metric"><h3>{col.upper()}</h3></div>' for col in df.columns[:5])}
        </div>
    </div>
    
    <div class="card">
        <h2>📋 Данные</h2>
        <table>
            <thead>
                <tr>{''.join(f'<th>{col}</th>' for col in df.columns)}</tr>
            </thead>
            <tbody>
                {''.join(f'<tr>{"".join(f"<td>{str(df.iloc[i][col])}</td>" for col in df.columns)}</tr>' for i in range(min(10, len(df))))}
            </tbody>
        </table>
    </div>
    
    <div class="card">
        <h2>📈 График</h2>
        <img src="chart.png" alt="График данных" class="chart">
    </div>
    
    <footer>
        <p>Generated by OpenClaw Data Analysis Workspace</p>
    </footer>
</body>
</html>
    """
    
    # Сохраняем HTML
    html_file = "reports/report.html"
    with open(html_file, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"[{datetime.now()}] HTML отчет сохранен в {html_file}")
    
    # Создаем график
    plt.figure(figsize=(12, 6))
    if len(df.columns) >= 2:
        plt.plot(df.index, df.iloc[:, 1].values, marker='o', linewidth=2, markersize=8)
        plt.title("Динамика данных")
        plt.xlabel("Index")
        plt.ylabel(df.columns[1])
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig("reports/chart.png", dpi=150, bbox_inches='tight')
        print(f"[{datetime.now()}] График сохранен в reports/chart.png")
    else:
        print("[!] Недостаточно данных для графика")
    
    print(f"[{datetime.now()}] Отчет успешно сгенерирован!")
    return html_file, "reports/chart.png"

if __name__ == "__main__":
    visualize()
